### ISSUE TITLE
Solution for 2016

### ISSUE THREAD

**Issue by Joeostr** [akaskela/WorkflowElements#2]
Is there an updated solution for on-prem 1612 (8.2.5.4)?

**Comment by Joeostr** [comment]
Im actually unable to import this solution in neither 8 nor 9 (on-prem). Also, if this solution is targeted for 9, then the webhook functionality is is an [OOB 9 feature](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/use-webhooks), no need an additional plugin.

![2019_11_15_11_12_32_Import_Solution](https://user-images.githubusercontent.com/31250068/68958021-42c7c300-0799-11ea-825d-51ed08d9e537.png)

**Comment by smeranda** [comment]
Same issue. Were you able to resolve. Can the solutions.xml file be manually changed to 9.0?

**Comment by sebastiensapet** [comment]
Same issue for me, do you find something ?

**Comment by fvakiliev** [comment]
Same issue for me, do you find something ?

**Comment by Mohfath** [comment]
Guys, 
In his page for the solution he has given a link for a version that works on 2016 and 9.
This is the site 
[https://kaskelasolutions.com](https://kaskelasolutions.com)


and this is the link:
[Solution for 2016](https://kaskelasolutions.blob.core.windows.net/kaskelasolutionsdownload/WorkflowElements_2_2_0.zip?st=2020-06-30T14%3A19%3A00Z&se=2025-07-01T14%3A19%3A00Z&sp=r&sv=2015-12-11&sr=b&sig=Sh8WsxW8C1z6cyzWqiDa860d2Vr68Na147SqCqBm6jc%3D)
