### ISSUE TITLE
Send Webhook

### ISSUE THREAD

**Issue by netRunner0** [akaskela/WorkflowElements#21]
Please close

**Comment by netRunner0** [comment]
The problem, as I understand it, is in html tags and brackets {}

More simple code - successfully sent.
As I understand it, the problem is in the inline menu

`{
  "chat_id": "87948826",
  "parse_mode": "html",
  "text":"🛎 Новая заявка <b>Заявка</b> за Квартал\n
\n
Сумма СФ: <b>Сумма₽</b>\n
Ставка: <b>Ставка%</b>\n
Комиссия: <b>Комиссия₽</b>\n
Агент: <b>Агент</b>\n
\n
Ставка (исп.): <b>ИСП СУММА%</b>\n
\n
Менеджер: <u>Менеджер</u>"}`

**Comment by akaskela** [comment]
Closed by request of OP
