### ISSUE TITLE
Call Webhook - RequestHeaders input is not used

### ISSUE THREAD

**Issue by JanPadysak** [akaskela/WorkflowElements#4]
Hello,

seems that the **RequestHeaders**  input argument is not used in the **WebHook.cs** activity code. 
[documentation](https://github.com/akaskela/WorkflowElements/wiki/Webhook-Call-Webhook), [Webhook activity implementation](https://github.com/akaskela/WorkflowElements/blob/master/Kaskela.WorkflowElements.Shared/Activities/WebHook.cs )

**Comment by JanPadysak** [comment]
I have created pull request with fix if you want to merge https://github.com/akaskela/WorkflowElements/pull/5

**Comment by akaskela** [comment]
Thanks for the fix. Your fix has been incorporated and closing this item.
